#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jan 20 14:11:22 2022

@author: livcornelissen
"""

import xarray as xr
import matplotlib as plt
import numpy as np

datapath = '/Users/livcornelissen/Documents/Study/UU/SOAC/SOAC-project/'
filename = 'ball_R_90'

data = xr.open_dataset(datapath + filename+'.nc')

#data [t,x,y]

vorticity = data.vorticity
u = data.u
v = data.v

u2 = u**2
v2 = v**2
uabs = np.sqrt(u**2 + v**2)
uabs2 = uabs**2
#mean values over time [x,y]
U_mean = u.mean(dim = 't')
V_mean = v.mean(dim = 't')
uabs_mean = uabs.mean(dim = 't')
#pertubations [t,x,y]
u_pert = u-U_mean
v_pert = v-V_mean
uabs_pert = uabs - uabs_mean

"""variance  of uabs [x,y]
sigma**2  """
sigma_2 = (uabs2).mean(dim = 't') - (uabs.mean(dim = 't'))**2 
sigma_reeks = ((uabs2.sum(dim = 't') -  (uabs.sum(dim = 't'))**2/np.shape(u)[0]))/np.shape(u)[0]



